apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: 1.0 (edge)
  creationTimestamp: null
  labels:
    io.eseedge.service: applicationinsights
  name: applicationinsights
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9940"
    port: 9940
    targetPort: 443
    nodePort: 30940
  selector:
    io.eseedge.service: applicationinsights
status:
  loadBalancer: {}
