apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: 1.0 (edge)
  creationTimestamp: null
  labels:
    io.eseedge.service: applicationinsights
  name: applicationinsights
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: applicationinsights
  strategy: {}
  template:
    metadata:
      annotations:
        eseedge.version: 1.0 (edge)
      creationTimestamp: null
      labels:
        io.eseedge.network/esenetwork: "true"
        io.eseedge.service: applicationinsights
    spec:
      containers:
      - name: applicationinsights
        image: eseregistryedge.azurecr.io/eseedge/applicationinsights:ese
        imagePullPolicy: "" 
        ports:
        - containerPort: 443
        resources:
          limits:
            memory: 1Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 1Gi
            ephemeral-storage: 100Mi
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
