apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: client
  name: client
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9998"
    port: 9998
    targetPort: 8080
    nodePort: 30998
  selector:
    io.eseedge.service: client
status:
  loadBalancer: {}
