apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: client
  name: client
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: client
  strategy: {}
  template:
    metadata:
      annotations:
        eseedge.version: "1.0"
      creationTimestamp: null
      labels:
        io.eseedge.service: client
    spec:
      containers:
      - name: client
        image: eseregistryedge.azurecr.io/eseedge/client:ese
        imagePullPolicy: Always        
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 1Gi
            ephemeral-storage: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10  
        tty: true
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
