apiVersion: v1
kind: Secret
metadata:
  name: functions-secret
  namespace: eseedge
type: Opaque
stringData:
  host.json: |-
    {
      "masterKey": {
        "name": "master",
        "value": "test1",
        "encrypted": false
      },
      "functionKeys": [ ]
    }
  httpTrigger.json: |-
    {
      "keys": [
        {
          "name": "default",
          "value": "test2",
          "encrypted": false
        }
      ]
    }
