apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: functions
  name: functions
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9972"
    port: 9972
    targetPort: 80
    nodePort: 30972
  selector:
    io.eseedge.service: functions
status:
  loadBalancer: {}
