apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: functions
  name: functions
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: functions
  strategy: {}
  template:
    metadata:
      annotations:
        eseedge.version: "1.0"
      creationTimestamp: null
      labels:
        io.eseedge.network/esenetwork: "true"
        io.eseedge.service: functions
    spec:
      containers:        
      - name: functions
        image: eseregistryedge.azurecr.io/eseedge/functions:ese
        volumeMounts:
        - name: secrets
          mountPath: "/azure-functions-host/Secrets"
          readOnly: true
        env:
        - name: AzureWebJobsSecretStorageType
          value: files
        - name: AzureWebJobsScriptRoot
          valueFrom:
            configMapKeyRef:
              name: functions-config
              key: AzureWebJobsScriptRoot
        - name: AzureFunctionsJobHost__Logging__Console__IsEnabled
          valueFrom:
            configMapKeyRef:
              name: functions-config
              key: AzureFunctionsJobHost__Logging__Console__IsEnabled
        - name: AzureWebJobsStorage
          valueFrom:
            configMapKeyRef:
              name: functions-config
              key: AzureWebJobsStorage             
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 2Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 2Gi
            ephemeral-storage: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10  
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: secrets
        secret:
          secretName: functions-secret
status: {}
