apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: fuseki
  name: fuseki
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9976"
    port: 9976
    targetPort: 3030
    nodePort: 30976
  selector:
    io.eseedge.service: fuseki
status:
  loadBalancer: {}
