apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: fuseki2
  name: fuseki2
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9977"
    port: 9977
    targetPort: 3030
    nodePort: 30977
  selector:
    io.eseedge.service: fuseki2
status:
  loadBalancer: {}
