apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: fuseki
  name: fuseki
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: fuseki
  strategy: {}
  template:
    metadata:
      annotations:
        eseedge.version: "1.0"
      creationTimestamp: null
      labels:
        io.eseedge.network/esenetwork: "true"
        io.eseedge.service: fuseki
    spec:
      containers:
      - name: fuseki
        image: eseregistryedge.azurecr.io/eseedge/fuseki:ese
        env:
        - name: JVM_ARGS
          valueFrom:
            configMapKeyRef:
              name: fuseki-config
              key: JVM_ARGS
        - name: FUSEKI_DATASET_1
          valueFrom:
            configMapKeyRef:
              name: fuseki-config
              key: FUSEKI_DATASET_1
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fuseki-secret
              key: password
        imagePullPolicy: "" 
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 2Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 2Gi
            ephemeral-storage: 100Mi
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
