apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: gremlinserver
  name: gremlinserver
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9995"
    port: 9995
    targetPort: 8182
    nodePort: 30995
  selector:
    io.eseedge.service: gremlinserver
status:
  loadBalancer: {}
