apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: keyphraseextraction
  name: keyphraseextraction
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9985"
    port: 9985
    targetPort: 5000
    nodePort: 30985
  selector:
    io.eseedge.service: keyphraseextraction
status:
  loadBalancer: {}
