apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: kibana
  name: kibana
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: kibana
  strategy: {}
  template:
    metadata:
      annotations:
        eseedge.version: "1.0"
      creationTimestamp: null
      labels:
        io.eseedge.network/esenetwork: "true"
        io.eseedge.service: kibana
    spec:
      enableServiceLinks: false
      containers:
      - name: kibana
        image: eseregistryedge.azurecr.io/eseedge/kibana:ese
        imagePullPolicy: Always
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://172.27.13.155:9200 # Please substitute the IP with the Internal IP of elasticsearch pod found via kubectl get pods -n eseedge -o wide
        - name: SERVER_NAME
          value: kibana
        - name: SERVER_REWRITEBASEPATH
          value: "false"        
        resources:
          limits:
            memory: 1Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 1Gi
            ephemeral-storage: 100Mi
        readinessProbe:
          httpGet:
            path: /api/status
            port: 5601
          initialDelaySeconds: 5
          timeoutSeconds: 10      
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
status: {}
