apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: languagedetection
  name: languagedetection
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: languagedetection
  strategy: {}
  template:
    metadata:
      annotations:
        eseedge.version: "1.0"
      creationTimestamp: null
      labels:
        io.eseedge.network/esenetwork: "true"
        io.eseedge.service: languagedetection
    spec:
      containers:
      - name: languagedetection
        image: eseregistryedge.azurecr.io/eseedge/languagedetection:ese
        env:
        - name: Eula
          valueFrom:
            configMapKeyRef:
              name: languagedetection-config
              key: Eula
        - name: Billing
          valueFrom:
            configMapKeyRef:
              name: languagedetection-config
              key: Billing
        - name: ApiKey
          valueFrom:
            secretKeyRef:
              name: languagedetection-secret
              key: apikey
        imagePullPolicy: "" 
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 3Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 3Gi
            ephemeral-storage: 100Mi
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10             
        tty: true
      imagePullSecrets:
      - name: regcred       
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
