apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: languagedetection
  name: languagedetection
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9984"
    port: 9984
    targetPort: 5000
    nodePort: 30984
  selector:
    io.eseedge.service: languagedetection
status:
  loadBalancer: {}
