apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: mongo
  name: mongo
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        eseedge.version: "1.0"
      creationTimestamp: null
      labels:
        io.eseedge.network/esenetwork: "true"
        io.eseedge.service: mongo
    spec:
      containers:
      - name: mongo
        image: eseregistryedge.azurecr.io/eseedge/mongo:ese
        imagePullPolicy: ""
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: 2Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 2Gi
            ephemeral-storage: 100Mi
        volumeMounts:
        - name: mongovolume
          mountPath: /data/db
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mongovolume
        hostPath:
          path: /tmp/mongo
status: {}
