apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: mongoexpress
  name: mongoexpress
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: mongoexpress
  strategy: {}
  template:
    metadata:
      annotations:
        eseedge.version: "1.0"
      creationTimestamp: null
      labels:
        io.eseedge.network/esenetwork: "true"      
        io.eseedge.service: mongoexpress
    spec:
      containers:
      - name: mongoexpress
        image: eseregistryedge.azurecr.io/eseedge/mongoexpress:ese
        imagePullPolicy: Always
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: $(MONGO_SERVICE_HOST)
        - name: ME_CONFIG_MONGODB_PORT
          value: $(MONGO_SERVICE_PORT)      
        resources:
          limits:
            memory: 1Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 1Gi
            ephemeral-storage: 100Mi
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
