apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: mongo
  name: mongo
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9993"
    port: 9993
    targetPort: 27017
    nodePort: 30993
  selector:
    io.eseedge.service: mongo
status:
  loadBalancer: {}
