apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: ocr
  name: ocr
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9969"
    port: 9969
    targetPort: 5000
    nodePort: 30969
  selector:
    io.eseedge.service: ocr
status:
  loadBalancer: {}
