apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: pipeline
  name: pipeline
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9991"
    port: 9991
    targetPort: 3000
    nodePort: 30991
  selector:
    io.eseedge.service: pipeline
status:
  loadBalancer: {}
