apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: pipelinedocuments
  name: pipelinedocuments
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9961"
    port: 9961
    targetPort: 3000
    nodePort: 30961
  selector:
    io.eseedge.service: pipelinedocuments
status:
  loadBalancer: {}
