apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: pipelinedocuments
  name: pipelinedocuments
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: pipelinedocuments
  strategy: {}
  template:
    metadata:
      annotations:
        eseedge.version: "1.0"
      creationTimestamp: null
      labels:
        io.eseedge.network/esenetwork: "true"
        io.eseedge.service: pipelinedocuments
    spec:
      containers:
      - name: pipelinedocuments
        image: eseregistryedge.azurecr.io/eseedge/pipelinedocuments:ese
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 1Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 1Gi
            ephemeral-storage: 100Mi
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
