apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: pipelineimages
  name: pipelineimages
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9962"
    port: 9962
    targetPort: 3000
    nodePort: 30962
  selector:
    io.eseedge.service: pipelineimages
status:
  loadBalancer: {}
