apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: server
  name: server
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9990"
    port: 9990
    targetPort: 3000
    nodePort: 30990
  selector:
    io.eseedge.service: server
status:
  loadBalancer: {}
