apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: sql
  name: sql
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9988"
    port: 9988
    targetPort: 1433
    nodePort: 30988
  selector:
    io.eseedge.service: sql
status:
  loadBalancer: {}
