apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: stanfordcorenlp
  name: stanfordcorenlp
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9987"
    port: 9987
    targetPort: 9000
    nodePort: 30987
  selector:
    io.eseedge.service: stanfordcorenlp
status:
  loadBalancer: {}
