apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: stanfordcorenlp
  name: stanfordcorenlp
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: stanfordcorenlp
  strategy: {}
  template:
    metadata:
      annotations:
        eseedge.version: "1.0"
      creationTimestamp: null
      labels:
        io.eseedge.network/esenetwork: "true"
        io.eseedge.service: stanfordcorenlp
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: stanfordcorenlp-config
              key: JAVA_OPTS
        - name: JAVA_XMX
          valueFrom:
            configMapKeyRef:
              name: stanfordcorenlp-config
              key: JAVA_XMX
        - name: TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: stanfordcorenlp-config
              key: TIMEOUT
        - name: LOGIN
          valueFrom:
            secretKeyRef:
              name: stanfordcorenlp-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: stanfordcorenlp-secret
              key: password
        name: stanfordcorenlp
        image: eseregistryedge.azurecr.io/eseedge/stanfordcorenlp:ese
        imagePullPolicy: ""
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: 6Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 6Gi
            ephemeral-storage: 100Mi
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
