apiVersion: v1
kind: Service
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: tika
  name: tika
  namespace: eseedge
spec:
  type: NodePort
  ports:
  - name: "9986"
    port: 9986
    targetPort: 9998
    nodePort: 30986
  selector:
    io.eseedge.service: tika
status:
  loadBalancer: {}
