apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    eseedge.version: "1.0"
  creationTimestamp: null
  labels:
    io.eseedge.service: tika
  name: tika
  namespace: eseedge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.eseedge.service: tika
  strategy: {}
  template:
    metadata:
      annotations:
        eseedge.version: "1.0"
      creationTimestamp: null
      labels:
        io.eseedge.network/esenetwork: "true"
        io.eseedge.service: tika
    spec:
      containers:
      - name: tika
        image: eseregistryedge.azurecr.io/eseedge/tika:ese
        imagePullPolicy: ""
        ports:
        - containerPort: 9998
        resources:
          limits:
            memory: 2Gi
            ephemeral-storage: 100Mi
          requests:
            memory: 2Gi
            ephemeral-storage: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 9998
          initialDelaySeconds: 5
          periodSeconds: 10      
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
