export const countries = [
    { name: 'Afghanistan', flag: 'af', capital: 'Kabul', people: 'Afghan,Afghanistani', wiki: 'https://en.wikipedia.org/wiki/Afghanistan', iso: 'AF', un: 'AFG' },	
    { name: 'Aland Islands', flag: 'ax', capital: 'Mariehamn', people: 'Ålandic,Ålandish,Ålänning,Åländare,Ahvenanmaalainen', wiki: 'https://en.wikipedia.org/wiki/%C3%85land_Islands', iso: '', un: '' },
    { name: 'Aland_Islands', flag: 'ax', capital: 'Mariehamn', people: 'Ålandic,Ålandish,Ålänning,Åländare,Ahvenanmaalainen', wiki: 'https://en.wikipedia.org/wiki/%C3%85land_Islands', iso: '', un: '' },	
    { name: 'Albania', flag: 'al', capital: 'Tirana', people: 'Albanian', wiki: 'https://en.wikipedia.org/wiki/Albania', iso: 'AL', un: 'ALB' },	
    { name: 'Algeria', flag: 'dz', capital: 'Algiers', people: 'Algerian', wiki: 'https://en.wikipedia.org/wiki/Algeria', iso: 'DZ', un: 'DZA' },	
    { name: 'American Samoa', flag: 'as', capital: 'Pago Pago', people: 'American Samoan,Samoan', wiki: 'https://en.wikipedia.org/wiki/American_Samoa', iso: 'AS', un: 'ASM' },	
    { name: 'American_Samoa', flag: 'as', capital: 'Pago Pago', people: 'American Samoan,Samoan', wiki: 'https://en.wikipedia.org/wiki/American_Samoa', iso: 'AS', un: 'ASM' },	
    { name: 'Andorra', flag: 'ad', capital: 'Andorra la Vella', people: 'Andorran', wiki: 'https://en.wikipedia.org/wiki/Andorra', iso: 'AD', un: 'AND' },	
    { name: 'Angola', flag: 'ao', capital: 'Luanda', people: 'Angolan', wiki: 'https://en.wikipedia.org/wiki/Angola', iso: 'AO', un: 'AGO' },
    { name: 'Anguilla', flag: 'ai', capital: 'The Valley', people: 'Anguillian', wiki: 'https://en.wikipedia.org/wiki/Anguilla', iso: 'AI', un: 'AIA' },
    { name: 'Antigua', flag: 'ag', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Antigua', iso: 'AG', un: 'ATG' },
    { name: 'Argentina', flag: 'ar', capital: 'Buenos Aires', people: 'Argentine,Argentinian,Argentinean', wiki: 'https://en.wikipedia.org/wiki/Argentina', iso: 'AR', un: 'ARG' },
    { name: 'Armenia', flag: 'am', capital: 'Yerevan', people: 'Armenian', wiki: 'https://en.wikipedia.org/wiki/Armenia', iso: 'AM', un: 'ARM' },
    { name: 'Aruba', flag: 'aw', capital: 'Oranjestad', people: 'Aruban', wiki: 'https://en.wikipedia.org/wiki/Aruba', iso: 'AW', un: 'ABW' },
    { name: 'Australia', flag: 'au', capital: 'Canberra', people: 'Australian,Aussie', wiki: 'https://en.wikipedia.org/wiki/Australia', iso: 'AU', un: 'AUS' },
    { name: 'Austria', flag: 'at', capital: 'Vienna', people: 'Austrian', wiki: 'https://en.wikipedia.org/wiki/Austria', iso: 'AT', un: 'AUT' },
    { name: 'Azerbaijan', flag: 'az', capital: 'Baku', people: 'Azerbaijani', wiki: 'https://en.wikipedia.org/wiki/Azerbaijan', iso: 'AZ', un: 'AZE' },
    { name: 'Bahamas', flag: 'bs', capital: 'Nassau', people: 'Bahamian', wiki: 'https://en.wikipedia.org/wiki/The_Bahamas', iso: 'BS', un: 'BHS' },
    { name: 'Bahrain', flag: 'bh', capital: 'Manama', people: 'Bahrani', wiki: 'https://en.wikipedia.org/wiki/Bahrain', iso: 'BH', un: 'BHR' },
    { name: 'Bangladesh', flag: 'bd', capital: 'Dhaka', people: 'Bangladeshi', wiki: 'https://en.wikipedia.org/wiki/Bangladesh', iso: 'BD', un: 'BGD' },
    { name: 'Barbados', flag: 'bb', capital: 'Bridgetown', people: 'Barbadian,Bajan', wiki: 'https://en.wikipedia.org/wiki/Barbados', iso: 'BB', un: 'BRB' },
    { name: 'Belarus', flag: 'by', capital: 'Minsk', people: 'Belarusian', wiki: 'https://en.wikipedia.org/wiki/Belarus', iso: 'BY', un: 'BLR' },
    { name: 'Belgium', flag: 'be', capital: 'Brussels', people: 'Belgian', wiki: 'https://en.wikipedia.org/wiki/Belgium', iso: 'BE', un: 'BEL' },
    { name: 'Belize', flag: 'bz', capital: 'Belmopan', people: 'Belizean', wiki: 'https://en.wikipedia.org/wiki/Belize', iso: 'BZ', un: 'BLZ' },
    { name: 'Benin', flag: 'bj', capital: 'Porto-Novo', people: 'Beninese', wiki: 'https://en.wikipedia.org/wiki/Benin', iso: 'BJ', un: 'BEN' },
    { name: 'Bermuda', flag: 'bm', capital: 'Hamilton', people: 'Bermudian', wiki: 'https://en.wikipedia.org/wiki/Bermuda', iso: 'BM', un: 'BMU' },
    { name: 'Bhutan', flag: 'bt', capital: 'Thimphu', people: 'Bhutanese', wiki: 'https://en.wikipedia.org/wiki/Bhutan', iso: 'BT', un: 'BTN' },
    { name: 'Bolivia', flag: 'bo', capital: 'Sucre,La Paz', people: 'Bolivian', wiki: 'https://en.wikipedia.org/wiki/Bolivia', iso: 'BO', un: 'BOL' },
    { name: 'Bosnia', flag: 'ba', capital: 'Sarajevo', people: 'Bosnian,Herzegovinian', wiki: 'https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina', iso: 'BA', un: 'BIH' },
    { name: 'Botswana', flag: 'bw', capital: 'Gaborone', people: 'Batswana,Motswana', wiki: 'https://en.wikipedia.org/wiki/Botswana', iso: 'BW', un: 'BWA' },
    { name: 'Bouvet Island', flag: 'bv', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Bouvet_Island', iso: 'BV', un: 'BVT' },
    { name: 'Bouvet_Island', flag: 'bv', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Bouvet_Island', iso: 'BV', un: 'BVT' },
    { name: 'Brazil', flag: 'br', capital: 'Brasilia', people: 'Brazilian', wiki: 'https://en.wikipedia.org/wiki/Brazil', iso: 'BR', un: 'BRA' },
    { name: 'British Virgin Islands', flag: 'vg', capital: 'Road Town', people: 'Virgin Islander', wiki: 'https://en.wikipedia.org/wiki/British_Virgin_Islands', iso: '', un: '' },
    { name: 'British_Virgin_Islands', flag: 'vg', capital: 'Road Town', people: 'Virgin Islander', wiki: 'https://en.wikipedia.org/wiki/British_Virgin_Islands', iso: '', un: '' },
    { name: 'Brunei', flag: 'bn', capital: 'Bandar Seri Begawan', people: 'Bruneian', wiki: 'https://en.wikipedia.org/wiki/Brunei', iso: 'BN', un: 'BRN' },
    { name: 'Bulgaria', flag: 'bg', capital: 'Sofia', people: 'Bulgarian', wiki: 'https://en.wikipedia.org/wiki/Bulgaria', iso: 'BG', un: 'BGR' },
    { name: 'Burkina Faso', flag: 'bf', capital: 'Ouagadougou', people: 'Burkinabé,Burkinabè,Burkinabe', wiki: 'https://en.wikipedia.org/wiki/Burkina_Faso', iso: 'BF', un: 'BFA' },
    { name: 'Burkina_Faso', flag: 'bf', capital: 'Ouagadougou', people: 'Burkinabé,Burkinabè,Burkinabe', wiki: 'https://en.wikipedia.org/wiki/Burkina_Faso', iso: 'BF', un: 'BFA' },
    { name: 'Burma', flag: 'mm', capital: 'Naypyidaw', people: 'Burmese,Myanma', wiki: 'https://en.wikipedia.org/wiki/Myanmar', iso: '', un: '' },
    { name:	'Myanmar', flag: 'mm', capital: 'Naypyidaw', people: 'Burmese,Myanma', wiki: 'https://en.wikipedia.org/wiki/Myanmar', iso: '', un: '' },
    { name: 'Burundi', flag: 'bi', capital: 'Bujumbura', people: 'Burundian', wiki: 'https://en.wikipedia.org/wiki/Burundi', iso: 'BI', un: 'BDI' },
    { name: 'Caicos Islands', flag: 'tc', capital: 'Cockburn Town', people: 'Turks,Caicos Islander', wiki: 'https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands', iso: '', un: '' },
    { name: 'Caicos_Islands', flag: 'tc', capital: 'Cockburn Town', people: 'Turks,Caicos Islander', wiki: 'https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands', iso: '', un: '' },
    { name: 'Cambodia', flag: 'kh', capital: 'Phnom Penh', people: 'Cambodian,Khmer', wiki: 'https://en.wikipedia.org/wiki/Cambodia', iso: 'KH', un: 'KHM' },
    { name: 'Cameroon', flag: 'cm', capital: 'Yaounde', people: 'Cameroonian', wiki: 'https://en.wikipedia.org/wiki/Cameroon', iso: 'CM', un: 'CMR' },
    { name: 'Canada', flag: 'ca', capital: 'Ottawa', people: 'Canadian', wiki: 'https://en.wikipedia.org/wiki/Canada', iso: 'CA', un: 'CAN' },
    { name: 'Cape Verde', flag: 'cv', capital: 'Praia', people: 'Cape Verdean,Cabo Verdean', wiki: 'https://en.wikipedia.org/wiki/Cape_Verde', iso: 'CV', un: 'CPV' },
    { name: 'Cape_Verde', flag: 'cv', capital: 'Praia', people: 'Cape Verdean,Cabo Verdean', wiki: 'https://en.wikipedia.org/wiki/Cape_Verde', iso: 'CV', un: 'CPV' },
    { name: 'Cayman Islands', flag: 'ky', capital: 'George Town', people: 'Caymanian', wiki: 'https://en.wikipedia.org/wiki/Cayman_Islands', iso: 'KY', un: 'CYM' },
    { name: 'Cayman_Islands', flag: 'ky', capital: 'George Town', people: 'Caymanian', wiki: 'https://en.wikipedia.org/wiki/Cayman_Islands', iso: 'KY', un: 'CYM' },
    { name: 'Central African Republic', flag: 'cf', capital: 'Bangui', people: 'Central African', wiki: 'https://en.wikipedia.org/wiki/Central_African_Republic', iso: 'CF', un: 'CAF' },
    { name: 'Central_African_Republic', flag: 'cf', capital: 'Bangui', people: 'Central African', wiki: 'https://en.wikipedia.org/wiki/Central_African_Republic', iso: 'CF', un: 'CAF' },
    { name: 'Chad', flag: 'td', capital: 'N\'Djamena', people: 'Chadian', wiki: 'https://en.wikipedia.org/wiki/Chad', iso: 'TD', un: 'TCD' },
    { name: 'Chile', flag: 'cl', capital: 'Santiago', people: 'Chilean', wiki: 'https://en.wikipedia.org/wiki/Chile', iso: 'CL', un: 'CHL' },
    { name: 'China', flag: 'cn', capital: 'Beijing', people: 'Chinese', wiki: 'https://en.wikipedia.org/wiki/China', iso: 'CN', un: 'CHN' },
    { name: 'Christmas Island', flag: 'cx', capital: 'Flying Fish Cove', people: 'Christmas Islander', wiki: 'https://en.wikipedia.org/wiki/Christmas_Island', iso: 'CX', un: 'CXR' },
    { name: 'Christmas_Island', flag: 'cx', capital: 'Flying Fish Cove', people: 'Christmas Islander', wiki: 'https://en.wikipedia.org/wiki/Christmas_Island', iso: 'CX', un: 'CXR' },
    { name: 'Cocos Islands', flag: 'cc', capital: 'West Island', people: '', wiki: 'https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands', iso: 'CC', un: 'CCK' },
    { name: 'Cocos_Islands', flag: 'cc', capital: 'West Island', people: '', wiki: 'https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands', iso: 'CC', un: 'CCK' },
    { name: 'Colombia', flag: 'co', capital: 'Bogota', people: 'Colombian', wiki: 'https://en.wikipedia.org/wiki/Colombia', iso: 'CO', un: 'COL' },
    { name: 'Comoros', flag: 'km', capital: 'Moroni', people: 'Comorian', wiki: 'https://en.wikipedia.org/wiki/Comoros', iso: 'KM', un: 'COM' },
    { name: 'Congo', flag: 'cd', capital: 'Kinshasa', people: 'Congolese', wiki: 'https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo', iso: 'CD', un: 'COD' },
    { name: 'Congo Brazzaville', flag: 'cg', capital: 'Brazzaville', people: 'Congolese', wiki: 'https://en.wikipedia.org/wiki/Republic_of_the_Congo', iso: '', un: '' },
    { name: 'Congo_Brazzaville', flag: 'cg', capital: 'Brazzaville', people: 'Congolese', wiki: 'https://en.wikipedia.org/wiki/Republic_of_the_Congo', iso: '', un: '' },
    { name: 'Cook Islands', flag: 'ck', capital: 'Avarua', people: 'Cook Islander', wiki: 'https://en.wikipedia.org/wiki/Cook_Islands', iso: 'CK', un: 'COK' },
    { name: 'Cook_Islands', flag: 'ck', capital: 'Avarua', people: 'Cook Islander', wiki: 'https://en.wikipedia.org/wiki/Cook_Islands', iso: 'CK', un: 'COK' },
    { name: 'Costa Rica', flag: 'cr', capital: 'San Jose', people: 'Costa Rican,Tico(a)', wiki: 'https://en.wikipedia.org/wiki/Costa_Rica', iso: 'CR', un: 'CRI' },
    { name: 'Costa_Rica', flag: 'cr', capital: 'San Jose', people: 'Costa Rican,Tico(a)', wiki: 'https://en.wikipedia.org/wiki/Costa_Rica', iso: 'CR', un: 'CRI' },
    { name: 'Cote Divoire', flag: 'ci', capital: 'Yamoussoukro,Abidjan', people: 'Ivorian', wiki: 'https://en.wikipedia.org/wiki/Ivory_Coast', iso: '', un: '' },
    { name: 'Cote_Divoire', flag: 'ci', capital: 'Yamoussoukro,Abidjan', people: 'Ivorian', wiki: 'https://en.wikipedia.org/wiki/Ivory_Coast', iso: '', un: '' },
    { name: 'Ivory Coast', flag: 'ci', capital: 'Yamoussoukro,Abidjan', people: 'Ivorian', wiki: 'https://en.wikipedia.org/wiki/Ivory_Coast', iso: '', un: '' },
    { name: 'Ivory_Coast', flag: 'ci', capital: 'Yamoussoukro,Abidjan', people: 'Ivorian', wiki: 'https://en.wikipedia.org/wiki/Ivory_Coast', iso: '', un: '' },
    { name: 'Croatia', flag: 'hr', capital: 'Zagreb', people: 'Croatian', wiki: 'https://en.wikipedia.org/wiki/Croatia', iso: 'HR', un: 'HRV' },
    { name: 'Cuba', flag: 'cu', capital: 'Havana', people: 'Cuban', wiki: 'https://en.wikipedia.org/wiki/Cuba', iso: 'CU', un: 'CUB' },
    { name: 'Cyprus', flag: 'cy', capital: 'Nicosia', people: 'Cypriot', wiki: 'https://en.wikipedia.org/wiki/Cyprus', iso: 'CY', un: 'CYP' },
    { name: 'Czech Republic', flag: 'cz', capital: 'Prague', people: 'Czech', wiki: 'https://en.wikipedia.org/wiki/Czech_Republic', iso: 'CZ', un: 'CZE' },
    { name: 'Czech_Republic', flag: 'cz', capital: 'Prague', people: 'Czech', wiki: 'https://en.wikipedia.org/wiki/Czech_Republic', iso: 'CZ', un: 'CZE' },
    { name: 'Denmark', flag: 'dk', capital: 'Copenhagen', people: 'Danish,Dane', wiki: 'https://en.wikipedia.org/wiki/Denmark', iso: 'DK', un: 'DNK' },
    { name: 'Djibouti', flag: 'dj', capital: 'Djibouti', people: 'Djiboutian', wiki: 'https://en.wikipedia.org/wiki/Djibouti', iso: 'DJ', un: 'DJI' },
    { name: 'Dominica', flag: 'dm', capital: 'Roseau', people: 'Dominican,Dominiquais', wiki: 'https://en.wikipedia.org/wiki/Dominica', iso: 'DM', un: 'DMA' },
    { name: 'Dominican Republic', flag: 'do', capital: 'Santo Domingo', people: 'Dominican,Quisqueyan', wiki: 'https://en.wikipedia.org/wiki/Dominican_Republic', iso: 'DO', un: 'DOM' },
    { name: 'Dominican_Republic', flag: 'do', capital: 'Santo Domingo', people: 'Dominican,Quisqueyan', wiki: 'https://en.wikipedia.org/wiki/Dominican_Republic', iso: 'DO', un: 'DOM' },
    { name: 'Ecuador', flag: 'ec', capital: 'Quito', people: 'Ecuadorian', wiki: 'https://en.wikipedia.org/wiki/Ecuador', iso: 'EC', un: 'ECU' },
    { name: 'Egypt', flag: 'eg', capital: 'Cairo', people: 'Egyptian', wiki: 'https://en.wikipedia.org/wiki/Egypt', iso: 'EG', un: 'EGY' },
    { name: 'El Salvador', flag: 'sv', capital: 'San Salvador', people: 'Salvadoran,Guanaco', wiki: 'https://en.wikipedia.org/wiki/El_Salvador', iso: 'SV', un: 'SLV' },
    { name: 'El_Salvador', flag: 'sv', capital: 'San Salvador', people: 'Salvadoran,Guanaco', wiki: 'https://en.wikipedia.org/wiki/El_Salvador', iso: 'SV', un: 'SLV' },
    { name: 'England', flag: 'gb eng', capital: 'London', people: 'English', wiki: 'https://en.wikipedia.org/wiki/England', iso: '', un: '' },
    { name: 'Equatorial Guinea', flag: 'gq', capital: 'Malabo', people: 'Equatorial Guinean,Equatoguinean', wiki: 'https://en.wikipedia.org/wiki/Equatorial_Guinea', iso: 'GQ', un: 'GNQ' },
    { name: 'Equatorial_Guinea', flag: 'gq', capital: 'Malabo', people: 'Equatorial Guinean,Equatoguinean', wiki: 'https://en.wikipedia.org/wiki/Equatorial_Guinea', iso: 'GQ', un: 'GNQ' },
    { name: 'Eritrea', flag: 'er', capital: 'Asmara', people: 'Eritrean', wiki: 'https://en.wikipedia.org/wiki/Eritrea', iso: 'ER', un: 'ERI' },
    { name: 'Estonia', flag: 'ee', capital: 'Tallinn', people: 'Estonian', wiki: 'https://en.wikipedia.org/wiki/Estonia', iso: 'EE', un: 'EST' },
    { name: 'Ethiopia', flag: 'et', capital: 'Addis Ababa', people: 'Ethiopian,Abyssinian', wiki: 'https://en.wikipedia.org/wiki/Ethiopia', iso: 'ET', un: 'ETH' },
    { name: 'European Union', flag: 'eu', capital: 'Brussels', people: 'European', wiki: 'https://en.wikipedia.org/wiki/European_Union', iso: '', un: '' },
    { name: 'European_Union', flag: 'eu', capital: 'Brussels', people: 'European', wiki: 'https://en.wikipedia.org/wiki/European_Union', iso: '', un: '' },
    { name: 'Falkland Islands', flag: 'fk', capital: 'Stanley', people: 'Falkland Islander', wiki: 'https://en.wikipedia.org/wiki/Falkland_Islands', iso: 'FK', un: 'FLK' },
    { name: 'Falkland_Islands', flag: 'fk', capital: 'Stanley', people: 'Falkland Islander', wiki: 'https://en.wikipedia.org/wiki/Falkland_Islands', iso: 'FK', un: 'FLK' },
    { name: 'Faroe Islands', flag: 'fo', capital: 'Torshavn', people: 'Faroe Islander,Faroese', wiki: 'https://en.wikipedia.org/wiki/Faroe_Islands', iso: 'FO', un: 'FRO' },
    { name: 'Faroe_Islands', flag: 'fo', capital: 'Torshavn', people: 'Faroe Islander,Faroese', wiki: 'https://en.wikipedia.org/wiki/Faroe_Islands', iso: 'FO', un: 'FRO' },
    { name: 'Fiji', flag: 'fj', capital: 'Suva', people: 'Fijian', wiki: 'https://en.wikipedia.org/wiki/Fiji', iso: 'FJ', un: 'FJI' },
    { name: 'Finland', flag: 'fi', capital: 'Helsinki', people: 'Finnish,Finn', wiki: 'https://en.wikipedia.org/wiki/Finland', iso: 'FI', un: 'FIN' },
    { name: 'France', flag: 'fr', capital: 'Paris', people: 'French', wiki: 'https://en.wikipedia.org/wiki/France', iso: 'FR', un: 'FRA' },
    { name: 'French Guiana', flag: 'gf', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/French_Guiana', iso: 'GF', un: 'GUF' },
    { name: 'French_Guiana', flag: 'gf', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/French_Guiana', iso: 'GF', un: 'GUF' },
    { name: 'French Polynesia', flag: 'pf', capital: 'Papeete', people: 'French Polynesian', wiki: 'https://en.wikipedia.org/wiki/French_Polynesia', iso: 'PF', un: 'PYF' },
    { name: 'French_Polynesia', flag: 'pf', capital: 'Papeete', people: 'French Polynesian', wiki: 'https://en.wikipedia.org/wiki/French_Polynesia', iso: 'PF', un: 'PYF' },
    { name: 'French Territories', flag: 'tf', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Overseas_France', iso: '', un: '' },
    { name: 'French_Territories', flag: 'tf', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Overseas_France', iso: '', un: '' },
    { name: 'Gabon', flag: 'ga', capital: 'Libreville', people: 'Gabonese,Gabonaise', wiki: 'https://en.wikipedia.org/wiki/Gabon', iso: 'GA', un: 'GAB' },
    { name: 'Gambia', flag: 'gm', capital: 'Banjul', people: 'Gambian', wiki: 'https://en.wikipedia.org/wiki/The_Gambia', iso: 'GM', un: 'GMB' },
    { name: 'Georgia', flag: 'ge', capital: 'Tbilisi', people: 'Georgian', wiki: 'https://en.wikipedia.org/wiki/Georgia_(country)', iso: 'GE', un: 'GEO' },
    { name: 'Germany', flag: 'de', capital: 'Berlin', people: 'German', wiki: 'https://en.wikipedia.org/wiki/Germany', iso: 'DE', un: 'DEU' },
    { name: 'Ghana', flag: 'gh', capital: 'Accra', people: 'Ghanaian', wiki: 'https://en.wikipedia.org/wiki/Ghana', iso: 'GH', un: 'GHA' },
    { name: 'Gibraltar', flag: 'gi', capital: 'Gibraltar', people: 'Gibraltarian,Llanito', wiki: 'https://en.wikipedia.org/wiki/Gibraltar', iso: 'GI', un: 'GIB' },
    { name: 'Greece', flag: 'gr', capital: 'Athens', people: 'Greek', wiki: 'https://en.wikipedia.org/wiki/Greece', iso: 'GR', un: 'GRC' },
    { name: 'Greenland', flag: 'gl', capital: 'Nuuk', people: 'Greenlander,Greenlandic', wiki: 'https://en.wikipedia.org/wiki/Greenland', iso: 'GL', un: 'GRL' },
    { name: 'Grenada', flag: 'gd', capital: 'St. George\'s', people: 'Grenadian', wiki: 'https://en.wikipedia.org/wiki/Grenada', iso: 'GD', un: 'GRD' },
    { name: 'Guadeloupe', flag: 'gp', capital: '', people: 'Guadeloupean', wiki: 'https://en.wikipedia.org/wiki/Guadeloupe', iso: 'GP', un: 'GLP' },
    { name: 'Guam', flag: 'gu', capital: 'Hagåtña', people: 'Guamanian', wiki: 'https://en.wikipedia.org/wiki/Guam', iso: 'GU', un: 'GUM' },
    { name: 'Guatemala', flag: 'gt', capital: 'Guatemala City', people: 'Guatemalan,Guatemalteco,Chapin', wiki: 'https://en.wikipedia.org/wiki/Guatemala', iso: 'GT', un: 'GTM' },
    { name: 'Guinea', flag: 'gn', capital: 'Conakry', people: 'Guinean', wiki: 'https://en.wikipedia.org/wiki/Guinea', iso: 'GN', un: 'GIN' },
    { name: 'Guinea-Bissau', flag: 'gw', capital: 'Bissau', people: 'Bissau-Guinean', wiki: 'https://en.wikipedia.org/wiki/Guinea-Bissau', iso: 'GW', un: 'GNB' },
    { name: 'Guyana', flag: 'gy', capital: 'Georgetown', people: 'Guyanese', wiki: 'https://en.wikipedia.org/wiki/Guyana', iso: 'GY', un: 'GUY' },
    { name: 'Haiti', flag: 'ht', capital: 'Port-au-Prince', people: 'Haitian', wiki: 'https://en.wikipedia.org/wiki/Haiti', iso: 'HT', un: 'HTI' },
    { name: 'Heard Island', flag: 'hm', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Heard_Island_and_McDonald_Islands', iso: 'HM', un: 'HMD' },
    { name: 'Heard_Island', flag: 'hm', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Heard_Island_and_McDonald_Islands', iso: 'HM', un: 'HMD' },
    { name: 'Honduras', flag: 'hn', capital: 'Tegucigalpa', people: 'Honduran,Catracho(a)', wiki: 'https://en.wikipedia.org/wiki/Honduras', iso: 'HN', un: 'HND' },
    { name: 'Hong Kong', flag: 'hk', capital: '', people: 'Hong Kongese,Hongkonger', wiki: 'https://en.wikipedia.org/wiki/Hong_Kong', iso: 'HK', un: 'HKG' },
    { name: 'Hong_Kong', flag: 'hk', capital: '', people: 'Hong Kongese,Hongkonger', wiki: 'https://en.wikipedia.org/wiki/Hong_Kong', iso: 'HK', un: 'HKG' },
    { name: 'Hungary', flag: 'hu', capital: 'Budapest', people: 'Hungarian', wiki: 'https://en.wikipedia.org/wiki/Hungary', iso: 'HU', un: 'HUN' },
    { name: 'Iceland', flag: 'is', capital: 'Reykjavík', people: 'Icelander', wiki: 'https://en.wikipedia.org/wiki/Iceland', iso: 'IS', un: 'ISL' },
    { name: 'India', flag: 'in', capital: 'New Delhi', people: 'Indian', wiki: 'https://en.wikipedia.org/wiki/India', iso: 'IN', un: 'IND' },
    { name: 'Indian Ocean Territory', flag: 'io', capital: 'Camp Justice', people: '', wiki: 'https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory', iso: '', un: '' },
    { name: 'Indian_Ocean_Territory', flag: 'io', capital: 'Camp Justice', people: '', wiki: 'https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory', iso: '', un: '' },
    { name: 'Indonesia', flag: 'id', capital: 'Jakarta', people: 'Indonesian', wiki: 'https://en.wikipedia.org/wiki/Indonesia', iso: 'ID', un: 'IDN' },
    { name: 'Iran', flag: 'ir', capital: 'Tehran', people: 'Iranian,Persian', wiki: 'https://en.wikipedia.org/wiki/Iran', iso: 'IR', un: 'IRN' },
    { name: 'Iraq', flag: 'iq', capital: 'Baghdad', people: 'Iraqi', wiki: 'https://en.wikipedia.org/wiki/Iraq', iso: 'IQ', un: 'IRQ' },
    { name: 'Ireland', flag: 'ie', capital: 'Dublin', people: 'Irish', wiki: 'https://en.wikipedia.org/wiki/Republic_of_Ireland', iso: 'IE', un: 'IRL' },
    { name: 'Israel', flag: 'il', capital: 'Jerusalem', people: 'Israeli', wiki: 'https://en.wikipedia.org/wiki/Israel', iso: 'IL', un: 'ISR' },
    { name: 'Italy', flag: 'it', capital: 'Rome', people: 'Italian', wiki: 'https://en.wikipedia.org/wiki/Italy', iso: 'IT', un: 'ITA' },
    { name: 'Jamaica', flag: 'jm', capital: 'Kingston', people: 'Jamaican', wiki: 'https://en.wikipedia.org/wiki/Jamaica', iso: 'JM', un: 'JAM' },
    { name: 'Jan Mayen', flag: 'sj', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Jan_Mayen', iso: '', un: '' },
    { name: 'Jan_Mayen', flag: 'sj', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Jan_Mayen', iso: '', un: '' },
    { name: 'Svalbard', flag: 'sj', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Svalbard', iso: '', un: '' },
    { name: 'Japan', flag: 'jp', capital: 'Tokyo', people: 'Japanese', wiki: 'https://en.wikipedia.org/wiki/Japan', iso: 'JP', un: 'JPN' },
    { name: 'Jordan', flag: 'jo', capital: 'Amman', people: 'Jordanian', wiki: 'https://en.wikipedia.org/wiki/Jordan', iso: 'JO', un: 'JOR' },
    { name: 'Kazakhstan', flag: 'kz', capital: 'Astana', people: 'Kazakhstani', wiki: 'https://en.wikipedia.org/wiki/Kazakhstan', iso: 'KZ', un: 'KAZ' },
    { name: 'Kenya', flag: 'ke', capital: 'Nairobi', people: 'Kenyan', wiki: 'https://en.wikipedia.org/wiki/Kenya', iso: 'KE', un: 'KEN' },
    { name: 'Kiribati', flag: 'ki', capital: 'Tarawa', people: 'I-Kiribati', wiki: 'https://en.wikipedia.org/wiki/Kiribati', iso: 'KI', un: 'KIR' },
    { name: 'Kuwait', flag: 'kw', capital: 'Kuwait City', people: 'Kuwaiti', wiki: 'https://en.wikipedia.org/wiki/Kuwait', iso: 'KW', un: 'KWT' },
    { name: 'Kyrgyzstan', flag: 'kg', capital: 'Bishkek', people: 'Kyrgyzstani,Kyrgyz', wiki: 'https://en.wikipedia.org/wiki/Kyrgyzstan', iso: 'KG', un: 'KGZ' },
    { name: 'Laos', flag: 'la', capital: 'Vientiane', people: 'Laotian,Lao', wiki: 'https://en.wikipedia.org/wiki/Laos', iso: 'LA', un: 'LAO' },
    { name: 'Latvia', flag: 'lv', capital: 'Riga', people: 'Latvian', wiki: 'https://en.wikipedia.org/wiki/Latvia', iso: 'LV', un: 'LVA' },
    { name: 'Lebanon', flag: 'lb', capital: 'Beirut', people: 'Lebanese', wiki: 'https://en.wikipedia.org/wiki/Lebanon', iso: 'LB', un: 'LBN' },
    { name: 'Lesotho', flag: 'ls', capital: 'Maseru', people: 'Mosotho,Basotho', wiki: 'https://en.wikipedia.org/wiki/Lesotho', iso: 'LS', un: 'LSO' },
    { name: 'Liberia', flag: 'lr', capital: 'Monrovia', people: 'Liberian', wiki: 'https://en.wikipedia.org/wiki/Liberia', iso: 'LR', un: 'LBR' },
    { name: 'Libya', flag: 'ly', capital: 'Tripoli', people: 'Libyan', wiki: 'https://en.wikipedia.org/wiki/Libya', iso: 'LY', un: 'LBY' },
    { name: 'Liechtenstein', flag: 'li', capital: 'Vaduz', people: 'Liechtensteiner', wiki: 'https://en.wikipedia.org/wiki/Liechtenstein', iso: 'LI', un: 'LIE' },
    { name: 'Lithuania', flag: 'lt', capital: 'Vilnius', people: 'Lithuanian', wiki: 'https://en.wikipedia.org/wiki/Lithuania', iso: 'LT', un: 'LTU' },
    { name: 'Luxembourg', flag: 'lu', capital: 'Luxembourg City', people: 'Luxembourgish,Luxembourger', wiki: 'https://en.wikipedia.org/wiki/Luxembourg', iso: 'LU', un: 'LUX' },
    { name: 'Macau', flag: 'mo', capital: '', people: 'Macanese', wiki: 'https://en.wikipedia.org/wiki/Macau', iso: 'MO', un: 'MAC' },
    { name: 'Macedonia', flag: 'mk', capital: 'Skopje', people: 'Macedonian', wiki: 'https://en.wikipedia.org/wiki/Republic_of_Macedonia', iso: 'MK', un: 'MKD' },
    { name: 'Madagascar', flag: 'mg', capital: 'Antananarivo', people: 'Malagasy', wiki: 'https://en.wikipedia.org/wiki/Madagascar', iso: 'MG', un: 'MDG' },
    { name: 'Malawi', flag: 'mw', capital: 'Lilongwe', people: 'Malawian', wiki: 'https://en.wikipedia.org/wiki/Malawi', iso: 'MW', un: 'MWI' },
    { name: 'Malaysia', flag: 'my', capital: 'Kuala Lumpur', people: 'Malaysian', wiki: 'https://en.wikipedia.org/wiki/Malaysia', iso: 'MY', un: 'MYS' },
    { name: 'Maldives', flag: 'mv', capital: 'Male', people: 'Maldivian', wiki: 'https://en.wikipedia.org/wiki/Maldives', iso: 'MV', un: 'MDV' },
    { name: 'Mali', flag: 'ml', capital: 'Bamako', people: 'Malian', wiki: 'https://en.wikipedia.org/wiki/Mali', iso: 'ML', un: 'MLI' },
    { name: 'Malta', flag: 'mt', capital: 'Valletta', people: 'Maltese', wiki: 'https://en.wikipedia.org/wiki/Malta', iso: 'MT', un: 'MLT' },
    { name: 'Marshall Islands', flag: 'mh', capital: 'Majuro', people: 'Marshallese', wiki: 'https://en.wikipedia.org/wiki/Marshall_Islands', iso: 'MH', un: 'MHL' },
    { name: 'Marshall_Islands', flag: 'mh', capital: 'Majuro', people: 'Marshallese', wiki: 'https://en.wikipedia.org/wiki/Marshall_Islands', iso: 'MH', un: 'MHL' },
    { name: 'Martinique', flag: 'mq', capital: '', people: 'Martinic(qu)an,Martiniquais,Martiniquaise', wiki: 'https://en.wikipedia.org/wiki/Martinique', iso: 'MQ', un: 'MTQ' },
    { name: 'Mauritania', flag: 'mr', capital: 'Nouakchott', people: 'Mauritanian', wiki: 'https://en.wikipedia.org/wiki/Mauritania', iso: 'MR', un: 'MRT' },
    { name: 'Mauritius', flag: 'mu', capital: 'Port Louis', people: 'Mauritian', wiki: 'https://en.wikipedia.org/wiki/Mauritius', iso: 'MU', un: 'MUS' },
    { name: 'Mayotte', flag: 'yt', capital: '', people: 'Maorais', wiki: 'https://en.wikipedia.org/wiki/Mayotte', iso: 'YT', un: 'MYT' },
    { name: 'Mexico', flag: 'mx', capital: 'Mexico City', people: 'Mexican', wiki: 'https://en.wikipedia.org/wiki/Mexico', iso: 'MX', un: 'MEX' },
    { name: 'Micronesia', flag: 'fm', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Micronesia', iso: 'FM', un: 'FSM' },
    { name: 'Moldova', flag: 'md', capital: 'Chisinau', people: 'Moldovan', wiki: 'https://en.wikipedia.org/wiki/Moldova', iso: 'MD', un: 'MDA' },
    { name: 'Monaco', flag: 'mc', capital: 'Monaco', people: 'Monegasque,Monacan', wiki: 'https://en.wikipedia.org/wiki/Monaco', iso: 'MC', un: 'MCO' },
    { name: 'Mongolia', flag: 'mn', capital: 'Ulaanbaatar', people: 'Mongolian,Mongol', wiki: 'https://en.wikipedia.org/wiki/Mongolia', iso: 'MN', un: 'MNG' },
    { name: 'Montenegro', flag: 'me', capital: 'Podgorica', people: 'Montenegrin', wiki: 'https://en.wikipedia.org/wiki/Montenegro', iso: 'ME', un: 'MNE' },
    { name: 'Montserrat', flag: 'ms', capital: 'Plymouth,Brades,Little Bay', people: 'Montserratian', wiki: 'https://en.wikipedia.org/wiki/Montserrat', iso: 'MS', un: 'MSR' },
    { name: 'Morocco', flag: 'ma', capital: 'Rabat', people: 'Moroccan', wiki: 'https://en.wikipedia.org/wiki/Morocco', iso: 'MA', un: 'MAR' },
    { name: 'Mozambique', flag: 'mz', capital: 'Maputo', people: 'Mozambican', wiki: 'https://en.wikipedia.org/wiki/Mozambique', iso: 'MZ', un: 'MOZ' },
    { name: 'Namibia', flag: 'na', capital: 'Windhoek', people: 'Namibian', wiki: 'https://en.wikipedia.org/wiki/Namibia', iso: 'NA', un: 'NAM' },
    { name: 'Nauru', flag: 'nr', capital: 'Yaren', people: 'Nauruan', wiki: 'https://en.wikipedia.org/wiki/Nauru', iso: 'NR', un: 'NRU' },
    { name: 'Nepal', flag: 'np', capital: 'Kathmandu', people: 'Nepalese', wiki: 'https://en.wikipedia.org/wiki/Nepal', iso: 'NP', un: 'NPL' },
    { name: 'Netherlands', flag: 'nl', capital: 'Amsterdam', people: 'Dutch', wiki: 'https://en.wikipedia.org/wiki/Netherlands', iso: 'NL', un: 'NLD' },
    { name: 'Netherlands Antilles', flag: 'an', capital: 'Willemstad', people: 'Netherlands Antillean', wiki: 'https://en.wikipedia.org/wiki/Netherlands_Antilles', iso: '', un: '' },
    { name: 'Netherlands_Antilles', flag: 'an', capital: 'Willemstad', people: 'Netherlands Antillean', wiki: 'https://en.wikipedia.org/wiki/Netherlands_Antilles', iso: '', un: '' },
    { name: 'New Caledonia', flag: 'nc', capital: 'Noumea', people: 'New Caledonian', wiki: 'https://en.wikipedia.org/wiki/New_Caledonia', iso: 'NC', un: 'NCL' },
    { name: 'New_Caledonia', flag: 'nc', capital: 'Noumea', people: 'New Caledonian', wiki: 'https://en.wikipedia.org/wiki/New_Caledonia', iso: 'NC', un: 'NCL' },
    { name: 'New Guinea', flag: 'pg', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/New_Guinea', iso: '', un: '' },
    { name: 'New_Guinea', flag: 'pg', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/New_Guinea', iso: '', un: '' },
    { name: 'New Zealand', flag: 'nz', capital: 'Wellington', people: 'New Zealander,Kiwi', wiki: 'https://en.wikipedia.org/wiki/New_Zealand', iso: 'NZ', un: 'NZL' },
    { name: 'New_Zealand', flag: 'nz', capital: 'Wellington', people: 'New Zealander,Kiwi', wiki: 'https://en.wikipedia.org/wiki/New_Zealand', iso: 'NZ', un: 'NZL' },
    { name: 'Nicaragua', flag: 'ni', capital: 'Managua', people: 'Nicaraguan', wiki: 'https://en.wikipedia.org/wiki/Nicaragua', iso: 'NI', un: 'NIC' },
    { name: 'Niger', flag: 'ne', capital: 'Niamey', people: 'Nigerien', wiki: 'https://en.wikipedia.org/wiki/Niger', iso: 'NE', un: 'NER' },
    { name: 'Nigeria', flag: 'ng', capital: 'Abuja', people: 'Nigerian', wiki: 'https://en.wikipedia.org/wiki/Nigeria', iso: 'NG', un: 'NGA' },	
    { name: 'Niue', flag: 'nu', capital: 'Alofi', people: 'Niuean', wiki: 'https://en.wikipedia.org/wiki/Niue', iso: 'NU', un: 'NIU' },
    { name: 'Norfolk Island', flag: 'nf', capital: 'Kingston', people: 'Norfolk Islander', wiki: 'https://en.wikipedia.org/wiki/Norfolk_Island', iso: 'NF', un: 'NFK' },
    { name: 'Norfolk_Island', flag: 'nf', capital: 'Kingston', people: 'Norfolk Islander', wiki: 'https://en.wikipedia.org/wiki/Norfolk_Island', iso: 'NF', un: 'NFK' },
    { name: 'North Korea', flag: 'kp', capital: 'Pyongyang', people: 'North Korean,Korean', wiki: 'https://en.wikipedia.org/wiki/North_Korea', iso: '', un: '' },
    { name: 'North_Korea', flag: 'kp', capital: 'Pyongyang', people: 'North Korean,Korean', wiki: 'https://en.wikipedia.org/wiki/North_Korea', iso: '', un: '' },
    { name: 'Northern Mariana Islands', flag: 'mp', capital: 'Saipan', people: 'Northern Mariana Islander,Mariana,Chamorro', wiki: 'https://en.wikipedia.org/wiki/Northern_Mariana_Islands', iso: 'MP', un: 'MNP' },
    { name: 'Northern_Mariana_Islands', flag: 'mp', capital: 'Saipan', people: 'Northern Mariana Islander,Mariana,Chamorro', wiki: 'https://en.wikipedia.org/wiki/Northern_Mariana_Islands', iso: 'MP', un: 'MNP' },
    { name: 'Norway', flag: 'no', capital: 'Oslo', people: 'Norwegian', wiki: 'https://en.wikipedia.org/wiki/Norway', iso: 'NO', un: 'NOR' },
    { name: 'Oman', flag: 'om', capital: 'Muscat', people: 'Omani', wiki: 'https://en.wikipedia.org/wiki/Oman', iso: 'OM', un: 'OMN' },
    { name: 'Pakistan', flag: 'pk', capital: 'Islamabad', people: 'Pakistani', wiki: 'https://en.wikipedia.org/wiki/Pakistan', iso: 'PK', un: 'PAK' },
    { name: 'Palau', flag: 'pw', capital: 'Ngerulmud', people: 'Palauan', wiki: 'https://en.wikipedia.org/wiki/Palau', iso: 'PW', un: 'PLW' },
    { name: 'Palestine', flag: 'ps', capital: 'Palestinian', people: '', wiki: 'https://en.wikipedia.org/wiki/State_of_Palestine', iso: 'PS', un: 'PSE' },
    { name: 'Panama', flag: 'pa', capital: 'Panama City', people: 'Panamanian', wiki: 'https://en.wikipedia.org/wiki/Panama', iso: 'PA', un: 'PAN' },
    { name: 'Paraguay', flag: 'py', capital: 'Asuncion', people: 'Paraguayan,Guarani', wiki: 'https://en.wikipedia.org/wiki/Paraguay', iso: 'PY', un: 'PRY' },
    { name: 'Peru', flag: 'pe', capital: 'Lima', people: 'Peruvian', wiki: 'https://en.wikipedia.org/wiki/Peru', iso: 'PE', un: 'PER' },
    { name: 'Philippines', flag: 'ph', capital: 'Manila', people: 'Filipino', wiki: 'https://en.wikipedia.org/wiki/Philippines', iso: 'PH', un: 'PHL' },
    { name: 'Pitcairn Islands', flag: 'pn', capital: 'Adamstown', people: 'Pitcairn Islander', wiki: 'https://en.wikipedia.org/wiki/Pitcairn_Islands', iso: 'PN', un: 'PCN' },
    { name: 'Pitcairn_Islands', flag: 'pn', capital: 'Adamstown', people: 'Pitcairn Islander', wiki: 'https://en.wikipedia.org/wiki/Pitcairn_Islands', iso: 'PN', un: 'PCN' },
    { name: 'Poland', flag: 'pl', capital: 'Warsaw', people: 'Polish,Pole', wiki: 'https://en.wikipedia.org/wiki/Poland', iso: 'PL', un: 'POL' },
    { name: 'Portugal', flag: 'pt', capital: 'Lisbon', people: 'Portuguese', wiki: 'https://en.wikipedia.org/wiki/Portugal', iso: 'PT', un: 'PRT' },
    { name: 'Puerto Rico', flag: 'pr', capital: 'San Juan', people: 'Puerto Rican,Boricua', wiki: 'https://en.wikipedia.org/wiki/Puerto_Rico', iso: 'PR', un: 'PRI' },
    { name: 'Puerto_Rico', flag: 'pr', capital: 'San Juan', people: 'Puerto Rican,Boricua', wiki: 'https://en.wikipedia.org/wiki/Puerto_Rico', iso: 'PR', un: 'PRI' },
    { name: 'Qatar', flag: 'qa', capital: 'Doha', people: 'Qatari', wiki: 'https://en.wikipedia.org/wiki/Qatar', iso: 'QA', un: 'QAT' },
    { name: 'Reunion', flag: 're', capital: '', people: 'Reunionese', wiki: 'https://en.wikipedia.org/wiki/R%C3%A9union', iso: 'RE', un: 'REU' },
    { name: 'Romania', flag: 'ro', capital: 'Bucharest', people: 'Romanian', wiki: 'https://en.wikipedia.org/wiki/Romania', iso: 'RO', un: 'ROU' },
    { name: 'Russia', flag: 'ru', capital: 'Moscow', people: 'Russian', wiki: 'https://en.wikipedia.org/wiki/Russia', iso: 'RU', un: 'RUS' },
    { name: 'Rwanda', flag: 'rw', capital: 'Kigali', people: 'Rwandan', wiki: 'https://en.wikipedia.org/wiki/Rwanda', iso: 'RW', un: 'RWA' },
    { name: 'Saint Helena', flag: 'sh', capital: 'Jamestown', people: 'Saint Helenian', wiki: 'https://en.wikipedia.org/wiki/Saint_Helena', iso: 'SH', un: 'SHN' },
    { name: 'Saint_Helena', flag: 'sh', capital: 'Jamestown', people: 'Saint Helenian', wiki: 'https://en.wikipedia.org/wiki/Saint_Helena', iso: 'SH', un: 'SHN' },
    { name: 'Saint Kitts and Nevis', flag: 'kn', capital: 'Basseterre', people: 'Kittitian,Nevisian', wiki: 'https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis', iso: 'KN', un: 'KNA' },
    { name: 'Saint_Kitts_and_Nevis', flag: 'kn', capital: 'Basseterre', people: 'Kittitian,Nevisian', wiki: 'https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis', iso: 'KN', un: 'KNA' },
    { name: 'Saint Lucia', flag: 'lc', capital: 'Castries', people: 'Saint Lucian', wiki: 'https://en.wikipedia.org/wiki/Saint_Lucia', iso: 'LC', un: 'LCA' },
    { name: 'Saint_Lucia', flag: 'lc', capital: 'Castries', people: 'Saint Lucian', wiki: 'https://en.wikipedia.org/wiki/Saint_Lucia', iso: 'LC', un: 'LCA' },
    { name: 'Saint Pierre', flag: 'pm', capital: 'Saint-Pierre', people: 'Saint-Pierrais,Miquelonnais,French', wiki: 'https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon', iso: 'PM', un: 'SPM' },
    { name: 'Saint_Pierre', flag: 'pm', capital: 'Saint-Pierre', people: 'Saint-Pierrais,Miquelonnais,French', wiki: 'https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon', iso: 'PM', un: 'SPM' },
    { name: 'Saint Vincent', flag: 'vc', capital: 'Kingstown', people: 'Vincentian,Vincy', wiki: 'https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines', iso: 'VC', un: 'VCT' },
    { name: 'Saint_Vincent', flag: 'vc', capital: 'Kingstown', people: 'Vincentian,Vincy', wiki: 'https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines', iso: 'VC', un: 'VCT' },
    { name: 'Samoa', flag: 'ws', capital: 'Apia', people: 'Samoan', wiki: 'https://en.wikipedia.org/wiki/Samoa', iso: 'WS', un: 'WSM' },
    { name: 'San Marino', flag: 'sm', capital: 'San Marino', people: 'Sammarinese', wiki: 'https://en.wikipedia.org/wiki/San_Marino', iso: 'SM', un: 'SMR' },
    { name: 'San_Marino', flag: 'sm', capital: 'San Marino', people: 'Sammarinese', wiki: 'https://en.wikipedia.org/wiki/San_Marino', iso: 'SM', un: 'SMR' },
    { name: 'Sandwich Islands', flag: 'gs', capital: 'King Edward Point', people: 'South Georgian,South Sandwich Islander', wiki: 'https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands', iso: '', un: '' },
    { name: 'Sandwich_Islands', flag: 'gs', capital: 'King Edward Point', people: 'South Georgian,South Sandwich Islander', wiki: 'https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands', iso: '', un: '' },
    { name: 'Sao Tome', flag: 'st', capital: 'Sao Tome', people: 'Sao Tomean,Santomean', wiki: 'https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe', iso: 'ST', un: 'STP' },
    { name: 'Sao_Tome', flag: 'st', capital: 'Sao Tome', people: 'Sao Tomean,Santomean', wiki: 'https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe', iso: 'ST', un: 'STP' },
    { name: 'Saudi Arabia', flag: 'sa', capital: 'Riyadh', people: 'Saudi Arabian,Saudi', wiki: 'https://en.wikipedia.org/wiki/Saudi_Arabia', iso: 'SA', un: 'SAU' },
    { name: 'Saudi_Arabia', flag: 'sa', capital: 'Riyadh', people: 'Saudi Arabian,Saudi', wiki: 'https://en.wikipedia.org/wiki/Saudi_Arabia', iso: 'SA', un: 'SAU' },
    { name: 'Scotland', flag: 'gb sct', capital: 'Edinburgh', people: 'Scottish,Scots', wiki: 'https://en.wikipedia.org/wiki/Scotland', iso: '', un: '' },
    { name: 'Senegal', flag: 'sn', capital: 'Dakar', people: 'Senegalese', wiki: 'https://en.wikipedia.org/wiki/Senegal', iso: 'SN', un: 'SEN' },
    { name: 'Serbia', flag: 'cs', capital: 'Belgrade', people: 'Serbian', wiki: 'https://en.wikipedia.org/wiki/Serbia', iso: 'RS', un: 'SRB' },
    { name: 'Serbia', flag: 'rs', capital: 'Belgrade', people: 'Serbian', wiki: 'https://en.wikipedia.org/wiki/Serbia', iso: 'RS', un: 'SRB' },
    { name: 'Seychelles', flag: 'sc', capital: 'Victoria', people: 'Seychellois,Seychelloise,Seselwa', wiki: 'https://en.wikipedia.org/wiki/Seychelles', iso: 'SC', un: 'SYC' },
    { name: 'Sierra Leone', flag: 'sl', capital: 'Freetown', people: 'Sierra Leonean', wiki: 'https://en.wikipedia.org/wiki/Sierra_Leone', iso: 'SL', un: 'SLE' },
    { name: 'Sierra_Leone', flag: 'sl', capital: 'Freetown', people: 'Sierra Leonean', wiki: 'https://en.wikipedia.org/wiki/Sierra_Leone', iso: 'SL', un: 'SLE' },
    { name: 'Singapore', flag: 'sg', capital: 'Singapore', people: 'Singaporean', wiki: 'https://en.wikipedia.org/wiki/Singapore', iso: 'SG', un: 'SGP' },
    { name: 'Slovakia', flag: 'sk', capital: 'Bratislava', people: 'Slovak,Slovakian', wiki: 'https://en.wikipedia.org/wiki/Slovakia', iso: 'SK', un: 'SVK' },
    { name: 'Slovenia', flag: 'si', capital: 'Ljubljana', people: 'Slovene', wiki: 'https://en.wikipedia.org/wiki/Slovenia', iso: 'SI', un: 'SVN' },
    { name: 'Solomon Islands', flag: 'sb', capital: 'Honiara', people: 'Solomon Islander', wiki: 'https://en.wikipedia.org/wiki/Solomon_Islands', iso: 'SB', un: 'SLB' },
    { name: 'Solomon_Islands', flag: 'sb', capital: 'Honiara', people: 'Solomon Islander', wiki: 'https://en.wikipedia.org/wiki/Solomon_Islands', iso: 'SB', un: 'SLB' },
    { name: 'Somalia', flag: 'so', capital: 'Mogadishu', people: 'Somali', wiki: 'https://en.wikipedia.org/wiki/Somalia', iso: 'SO', un: 'SOM' },
    { name: 'South Africa', flag: 'za', capital: 'Pretoria,Bloemfontein,Cape Town', people: 'South African', wiki: 'https://en.wikipedia.org/wiki/South_Africa', iso: 'ZA', un: 'ZAF' },
    { name: 'South_Africa', flag: 'za', capital: 'Pretoria,Bloemfontein,Cape Town', people: 'South African', wiki: 'https://en.wikipedia.org/wiki/South_Africa', iso: 'ZA', un: 'ZAF' },
    { name: 'South Korea', flag: 'kr', capital: 'Seoul', people: 'South Korean,Korean', wiki: 'https://en.wikipedia.org/wiki/South_Korea', iso: '', un: '' },
    { name: 'South_Korea', flag: 'kr', capital: 'Seoul', people: 'South Korean,Korean', wiki: 'https://en.wikipedia.org/wiki/South_Korea', iso: '', un: '' },
    { name: 'Spain', flag: 'es', capital: 'Madrid', people: 'Spanish,Spaniard', wiki: 'https://en.wikipedia.org/wiki/Spain', iso: 'ES', un: 'ESP' },
    { name: 'Sri Lanka', flag: 'lk', capital: 'Sri Jayawardenepura Kotte', people: 'Sri Lankan', wiki: 'https://en.wikipedia.org/wiki/Sri_Lanka', iso: 'LK', un: 'LKA' },
    { name: 'Sri_Lanka', flag: 'lk', capital: 'Sri Jayawardenepura Kotte', people: 'Sri Lankan', wiki: 'https://en.wikipedia.org/wiki/Sri_Lanka', iso: 'LK', un: 'LKA' },
    { name: 'Sudan', flag: 'sd', capital: 'Khartoum', people: 'Sudanese', wiki: 'https://en.wikipedia.org/wiki/Sudan', iso: 'SD', un: 'SDN' },
    { name: 'Suriname', flag: 'sr', capital: 'Paramaribo', people: 'Surinamese', wiki: 'https://en.wikipedia.org/wiki/Suriname', iso: 'SR', un: 'SUR' },
    { name: 'Swaziland', flag: 'sz', capital: 'Mbabane,Lobamba', people: 'Swazi', wiki: 'https://en.wikipedia.org/wiki/Eswatini', iso: '', un: '' },
    { name: 'Sweden', flag: 'se', capital: 'Stockholm', people: 'Swedish,Swede', wiki: 'https://en.wikipedia.org/wiki/Sweden', iso: 'SE', un: 'SWE' },
    { name: 'Switzerland', flag: 'ch', capital: 'Bern', people: 'Swiss', wiki: 'https://en.wikipedia.org/wiki/Switzerland', iso: 'CH', un: 'CHE' },
    { name: 'Syria', flag: 'sy', capital: 'Damascus', people: 'Syrian', wiki: 'https://en.wikipedia.org/wiki/Syria', iso: 'SY', un: 'SYR' },
    { name: 'Taiwan', flag: 'tw', capital: 'Taipei', people: 'Taiwanese', wiki: 'https://en.wikipedia.org/wiki/Taiwan', iso: 'TW', un: 'TWN' },
    { name: 'Tajikistan', flag: 'tj', capital: 'Dushanbe', people: 'Tajikistani', wiki: 'https://en.wikipedia.org/wiki/Tajikistan', iso: 'TJ', un: 'TJK' },
    { name: 'Tanzania', flag: 'tz', capital: 'Dodoma', people: 'Tanzanian', wiki: 'https://en.wikipedia.org/wiki/Tanzania', iso: 'TZ', un: 'TZA' },
    { name: 'Thailand', flag: 'th', capital: 'Bangkok', people: 'Thai,Siamese', wiki: 'https://en.wikipedia.org/wiki/Thailand', iso: 'TH', un: 'THA' },
    { name: 'Timorleste', flag: 'tl', capital: 'Dili', people: 'East Timorese,Timorese,Maubere', wiki: 'https://en.wikipedia.org/wiki/East_Timor', iso: 'TL', un: 'TLS' },
    { name: 'Togo', flag: 'tg', capital: 'Lome', people: 'Togolese', wiki: 'https://en.wikipedia.org/wiki/Togo', iso: 'TG', un: 'TGO' },
    { name: 'Tokelau', flag: 'tk', capital: '', people: 'Tokelauan', wiki: 'https://en.wikipedia.org/wiki/Tokelau', iso: 'TK', un: 'TKL' },
    { name: 'Tonga', flag: 'to', capital: 'Nukuʻalofa', people: 'Tongan', wiki: 'https://en.wikipedia.org/wiki/Tonga', iso: 'TO', un: 'TON' },
    { name: 'Trinidad', flag: 'tt', capital: 'Port of Spain', people: 'Trinidadians,Tobagonians,Trini,Trinbagonian', wiki: 'https://en.wikipedia.org/wiki/Trinidad_and_Tobago', iso: 'TT', un: 'TTO' },
    { name: 'Tunisia', flag: 'tn', capital: 'Tunis', people: 'Tunisian', wiki: 'https://en.wikipedia.org/wiki/Tunisia', iso: 'TN', un: 'TUN' },
    { name: 'Turkey', flag: 'tr', capital: 'Ankara', people: 'Turkish', wiki: 'https://en.wikipedia.org/wiki/Turkey', iso: 'TR', un: 'TUR' },
    { name: 'Turkmenistan', flag: 'tm', capital: 'Ashgabat', people: 'Turkmen', wiki: 'https://en.wikipedia.org/wiki/Turkmenistan', iso: 'TM', un: 'TKM' },
    { name: 'Tuvalu', flag: 'tv', capital: 'Funafuti', people: 'Tuvaluan', wiki: 'https://en.wikipedia.org/wiki/Tuvalu', iso: 'TV', un: 'TUV' },
    { name: 'United Arab Emirates', flag: 'ae', capital: 'Abu Dhabi', people: 'Emirati', wiki: 'https://en.wikipedia.org/wiki/United_Arab_Emirates', iso: 'AE', un: 'ARE' },
    { name: 'United_Arab_Emirates', flag: 'ae', capital: 'Abu Dhabi', people: 'Emirati', wiki: 'https://en.wikipedia.org/wiki/United_Arab_Emirates', iso: 'AE', un: 'ARE' },
    { name: 'Uganda', flag: 'ug', capital: 'Kampala', people: 'Ugandan', wiki: 'https://en.wikipedia.org/wiki/Uganda', iso: 'UG', un: 'UGA' },
    { name: 'Ukraine', flag: 'ua', capital: 'Kiev', people: 'Ukrainian', wiki: 'https://en.wikipedia.org/wiki/Ukraine', iso: 'UA', un: 'UKR' },
    { name: 'United Kingdom', flag: 'gb', capital: 'London', people: 'British,Briton', wiki: 'https://en.wikipedia.org/wiki/United_Kingdom', iso: 'GB', un: 'GBR' },
    { name: 'United_Kingdom', flag: 'gb', capital: 'London', people: 'British,Briton', wiki: 'https://en.wikipedia.org/wiki/United_Kingdom', iso: 'GB', un: 'GBR' },
    { name: 'United States', flag: 'us', capital: 'Washington', people: 'American', wiki: 'https://en.wikipedia.org/wiki/United_States', iso: 'US', un: 'USA' },
    { name: 'United_States', flag: 'us', capital: 'Washington', people: 'American', wiki: 'https://en.wikipedia.org/wiki/United_States', iso: 'US', un: 'USA' },
    { name: 'Uruguay', flag: 'uy', capital: 'Montevideo', people: 'Oriental,Uruguayan', wiki: 'https://en.wikipedia.org/wiki/Uruguay', iso: 'UY', un: 'URY' },	
    { name: 'US Minor Islands', flag: 'um', capital: '', people: 'American Islander', wiki: 'https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands', iso: 'UM', un: 'UMI' },
    { name: 'US_Minor_Islands', flag: 'um', capital: '', people: 'American Islander', wiki: 'https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands', iso: 'UM', un: 'UMI' },
    { name: 'US Virgin Islands', flag: 'vi', capital: 'Charlotte Amalie', people: 'Virgin Islander', wiki: 'https://en.wikipedia.org/wiki/United_States_Virgin_Islands', iso: '', un: '' },
    { name: 'US_Virgin_Islands', flag: 'vi', capital: 'Charlotte Amalie', people: 'Virgin Islander', wiki: 'https://en.wikipedia.org/wiki/United_States_Virgin_Islands', iso: '', un: '' },
    { name: 'Uzbekistan', flag: 'uz', capital: 'Tashkent', people: 'Uzbek', wiki: 'https://en.wikipedia.org/wiki/Uzbekistan', iso: 'UZ', un: 'UZB' },
    { name: 'Vanuatu', flag: 'vu', capital: 'Port Vila', people: 'Ni-Vanuatu', wiki: 'https://en.wikipedia.org/wiki/Vanuatu', iso: 'VU', un: 'VUT' },
    { name: 'Vatican City', flag: 'va', capital: 'Vatican City', people: '', wiki: 'https://en.wikipedia.org/wiki/Vatican_City', iso: '', un: '' },
    { name: 'Vatican_City', flag: 'va', capital: 'Vatican City', people: '', wiki: 'https://en.wikipedia.org/wiki/Vatican_City', iso: '', un: '' },
    { name: 'Venezuela', flag: 've', capital: 'Caracas', people: 'Venezuelan', wiki: 'https://en.wikipedia.org/wiki/Venezuela', iso: 'VE', un: 'VEN' },
    { name: 'Vietnam', flag: 'vn', capital: 'Hanoi', people: 'Vietnamese', wiki: 'https://en.wikipedia.org/wiki/Vietnam', iso: 'VN', un: 'VNM' },
    { name: 'Wales', flag: 'gb wls', capital: 'Cardiff', people: 'Welsh', wiki: 'https://en.wikipedia.org/wiki/Wales', iso: '', un: '' },
    { name: 'Wallis and Futuna', flag: 'wf', capital: 'Mata-Utu', people: 'Wallisian,Futunan', wiki: 'https://en.wikipedia.org/wiki/Wallis_and_Futuna', iso: 'WF', un: 'WLF' },
    { name: 'Wallis_and_Futuna', flag: 'wf', capital: 'Mata-Utu', people: 'Wallisian,Futunan', wiki: 'https://en.wikipedia.org/wiki/Wallis_and_Futuna', iso: 'WF', un: 'WLF' },
    { name: 'Western Sahara', flag: 'eh', capital: '', people: '', wiki: 'https://en.wikipedia.org/wiki/Western_Sahara', iso: 'EH', un: 'ESH' },
    { name: 'Yemen', flag: 'ye', capital: 'Sana\'a', people: 'Yemeni,Yemenite', wiki: 'https://en.wikipedia.org/wiki/Yemen', iso: 'YE', un: 'YEM' },
    { name: 'Zambia', flag: 'zm', capital: 'Lusaka', people: 'Zambian', wiki: 'https://en.wikipedia.org/wiki/Zambia', iso: 'ZM', un: 'ZMB' },
    { name: 'Zimbabwe', flag: 'zw', capital: 'Harare', people: 'Zimbabwean,Zimbo', wiki: 'https://en.wikipedia.org/wiki/Zimbabwe', iso: 'ZW', un: 'ZWE' }
];