//Collections
export const READ_COLLECTIONS_LOADING = 'READ_COLLECTIONS_LOADING';
export const READ_COLLECTIONS_SUCCESS = 'READ_COLLECTIONS_SUCCESS';
export const READ_COLLECTIONS_FAILURE = 'READ_COLLECTIONS_FAILURE';

//DocSearch
export const READ_DOCSEARCHRESULTS_LOADING = 'READ_DOCSEARCHRESULTS_LOADING';
export const READ_DOCSEARCHRESULTS_SUCCESS = 'READ_DOCSEARCHRESULTS_SUCCESS';
export const READ_DOCSEARCHRESULTS_FAILURE = 'READ_DOCSEARCHRESULTS_FAILURE';

//Documents
export const READ_DOCUMENTS_LOADING = 'READ_DOCUMENTS_LOADING';
export const READ_DOCUMENTS_SUCCESS = 'READ_DOCUMENTS_SUCCESS';
export const READ_DOCUMENTS_FAILURE = 'READ_DOCUMENTS_FAILURE';

//Entities
export const READ_ENTITIES_LOADING = 'READ_ENTITIES_LOADING';
export const READ_ENTITIES_SUCCESS = 'READ_ENTITIES_SUCCESS';
export const READ_ENTITIES_FAILURE = 'READ_ENTITIES_FAILURE';

//GraphSearch
export const READ_GRAPHSEARCHRESULTS_LOADING = 'READ_GRAPHSEARCHRESULTS_LOADING';
export const READ_GRAPHSEARCHRESULTS_SUCCESS = 'READ_GRAPHSEARCHRESULTS_SUCCESS';
export const READ_GRAPHSEARCHRESULTS_FAILURE = 'READ_GRAPHSEARCHRESULTS_FAILURE';

//Hierarchies
export const READ_HIERARCHIES_LOADING = 'READ_HIERARCHIES_LOADING';
export const READ_HIERARCHIES_SUCCESS = 'READ_HIERARCHIES_SUCCESS';
export const READ_HIERARCHIES_FAILURE = 'READ_HIERARCHIES_FAILURE';

//Home
export const READ_HOME_LOADING = 'READ_HOME_LOADING';
export const READ_HOME_SUCCESS = 'READ_HOME_SUCCESS';
export const READ_HOME_FAILURE = 'READ_HOME_FAILURE';

export const READ_HOMESEARCHRESULTS_LOADING = 'READ_HOMESEARCHRESULTS_LOADING';
export const READ_HOMESEARCHRESULTS_SUCCESS = 'READ_HOMESEARCHRESULTS_SUCCESS';
export const READ_HOMESEARCHRESULTS_FAILURE = 'READ_HOMESEARCHRESULTS_FAILURE';

//Insights
export const READ_INSIGHTS_LOADING = 'READ_INSIGHTS_LOADING';
export const READ_INSIGHTS_SUCCESS = 'READ_INSIGHTS_SUCCESS';
export const READ_INSIGHTS_FAILURE = 'READ_INSIGHTS_FAILURE';

//TextSearch
export const READ_TEXTSEARCHRESULTS_LOADING = 'READ_TEXTSEARCHRESULTS_LOADING';
export const READ_TEXTSEARCHRESULTS_SUCCESS = 'READ_TEXTSEARCHRESULTS_SUCCESS';
export const READ_TEXTSEARCHRESULTS_FAILURE = 'READ_TEXTSEARCHRESULTS_FAILURE';

//Topics
export const READ_TOPICS_LOADING = 'READ_TOPICS_LOADING';
export const READ_TOPICS_SUCCESS = 'READ_TOPICS_SUCCESS';
export const READ_TOPICS_FAILURE = 'READ_TOPICS_FAILURE';

//Users
export const READ_USERS_LOADING = 'READ_USERS_LOADING';
export const READ_USERS_SUCCESS = 'READ_USERS_SUCCESS';
export const READ_USERS_FAILURE = 'READ_USERS_FAILURE';

//Pictures
export const READ_PICTURES_LOADING = 'READ_PICTURES_LOADING';
export const READ_PICTURES_SUCCESS = 'READ_PICTURES_SUCCESS';
export const READ_PICTURES_FAILURE = 'READ_PICTURES_FAILURE';

//Videos
export const READ_VIDEOS_LOADING = 'READ_VIDEOS_LOADING';
export const READ_VIDEOS_SUCCESS = 'READ_VIDEOS_SUCCESS';
export const READ_VIDEOS_FAILURE = 'READ_VIDEOS_FAILURE';